<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2023-02-10T18:47:01+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.editor.ckeditor4.plugins.selected
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Nanaimo Archives',
            'seo' => [
                'canonical_url' => 'https://dev1.nanaimoarchives.ca/',
                'canonical_url_alternative' => '',
                'canonical_tag' => [
                    'enabled' => true,
                ],
            ],
            'editor' => [
                'concrete' => [
                    'enable_filemanager' => true,
                    'enable_sitemap' => true,
                ],
                'ckeditor4' => [
                    'plugins' => [
                        'selected' => [
                            'concretefilemanager',
                            'concreteinline',
                            'concreteuploadimage',
                            'dialogadvtab',
                            'divarea',
                            'floatingspace',
                            'normalizeonchange',
                            'resize',
                            'toolbar',
                            'wysiwygarea',
                            'a11yhelp',
                            'autogrow',
                            'basicstyles',
                            'colorbutton',
                            'colordialog',
                            'concretelink',
                            'concretestyles',
                            'contextmenu',
                            'elementspath',
                            'enterkey',
                            'entities',
                            'font',
                            'format',
                            'horizontalrule',
                            'htmlwriter',
                            'image',
                            'indentblock',
                            'indentlist',
                            'justify',
                            'list',
                            'liststyle',
                            'magicline',
                            'removeformat',
                            'showblocks',
                            'showborders',
                            'sourcedialog',
                            'sourcearea',
                            'stylescombo',
                            'tab',
                            'table',
                            'tableresize',
                            'tableselection',
                            'tabletools',
                            'undo',
                        ],
                    ],
                ],
            ],
        ],
    ],
];
